app:
  name: "bitcoinmarket"
  domain: "bitcoinmarket.pro"
  subdomain: "www"
ssl:
  enabled: true
  email: "support@bitcoinmarket.pro"
images:
  peatio: dreadedzombie/peatio:2.1.20
  barong: rubykube/barong:2.0.51
  frontend: bitcoinmarket/ui:latest
  tower: rubykube/tower:0.1.17
  postmaster: quay.io/openware/postmaster:0.0.3
  arke: rubykube/arke:0.1.5
vendor:
  frontend: https://github.com/rubykube/mikroapp.git
storage:
  provider: "Google"
  bucketName: "microkube-barong-docs-bucket"
  accessKey: "**********"
  secretKey: "**********"
terraform:
  credentials: "~/safe/microkube.json"
  project: "example-microkube"
  region: "europe-west4"
  zone: "europe-west4-a"
  instance_name: "microkube-cloud"
  machine_type: "n1-standard-4"
  image: "debian-cloud/debian-9"
twilio:
  phone_number: "+12018904539"
  account_sid: "AC645d48e3baa361bf10337b569477f4d3"
  auth_token: "0d32411719ec6abbb2ed8e420640337e"
sendgrid_api_key: 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
arke:
  strategy:
    type: 'copy'
    pair: 'ETHUSD'
    target:
      driver: rubykube
      host: 'http://www.app.local'
      name: John
      key: changeme
      secret: changeme
    sources:
      - driver: bitfinex
        name: Joe
        key: changeme
        secret: changeme
