version: '3.6'

services:
  peatio:
    image: "dreadedzombie/peatio:2.1.20"
    env_file:
      - ../config/peatio.env
    expose:
      - "8000"
    volumes:
      - ../config/peatio/seed:/opt/peatio/config/seed
      - ../config/peatio/management_api_v1.yml:/opt/peatio/config/management_api_v1.yml
      - ../config/peatio/plugins.yml:/opt/peatio/config/plugins.yml
    labels: {}
    command: bash -c "bin/link_config && bundle exec puma --config config/puma.rb"

  barong:
    image: "rubykube/barong:2.0.51"
    env_file:
      - ../config/barong.env
    ports:
      - "8001:8001"
    volumes:
      - ../config/secrets:/secrets:ro
      - ../config/barong/seeds.yml:/home/app/config/seeds.yml
      - ../config/barong/authz_rules.yml:/home/app/config/authz_rules.yml
