version: '3.6'

services:
  proxy:
    image: traefik:1.7.6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - ../config/acme.json:/acme.json
    networks:
      default:
        aliases:
          - www.bitcoinmarket.pro
          - peatio.bitcoinmarket.pro
          - ws.ranger.bitcoinmarket.pro
          - eth.bitcoinmarket.pro
          - tower.bitcoinmarket.pro
          - monitor.bitcoinmarket.pro
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: monitor.bitcoinmarket.pro'
      traefik.port: 8080
